name       : lwqq
version    : 0.6.1
release    : 2
source     :
    - https://github.com/xiehuc/lwqq/archive/v0.6.1.tar.gz : 9de1c4efa4ddfb7d05654a5740e9743a5e51b71b42acd2e330263939f3fc5cf8
license    : GPL-3.0
component  : programming
summary    : a library for the webqq protocol
description: |
    a libtrary for the webqq protocol
builddeps  :
    - pkgconfig(mozjs-17.0)
    - pkgconfig(sqlite3)
    - libev-devel
setup      : |
    %cmake -DLIB_INSTALL_DIR=lib64 .
build      : |
    %make
install    : |-
    %make_install
    rm $installdir/usr/lib64/liblwqq.a